version: ~> 1.0 # needed for imports

import: scala/scala-dev:travis/default.yml

language: scala

scala: 2.13.8

env:
  global:
    - ADOPTOPENJDK=8

script:
  - sbt core/publishLocal plugin/publishLocal
